# Generated by Django 2.0.3 on 2018-07-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default="that's girl")),
                ('singer', models.TextField(default='shabbyboy')),
                ('lastMotifydate', models.DateField(auto_now=True)),
                ('createdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
